name: Run Python Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '5 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        DISCORD_DEFAULT_PING: ${{ secrets.DISCORD_DEFAULT_PING }}
        DISCORD_EASY_PING: ${{ secrets.DISCORD_EASY_PING }}
        DISCORD_MEDIUM_PING: ${{ secrets.DISCORD_MEDIUM_PING }}
        DISCORD_HARD_PING: ${{ secrets.DISCORD_HARD_PING }}
        STUDY_PLAN_START_DATE: ${{ secrets.STUDY_PLAN_START_DATE }}
      run: |
        python main.py
